[package]
name = "puissance4"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
piston_window = "0.120.0"
image = "0.23.0"
vecmath = "1.0.0"
